/*
 * 
 * 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * 
 * 
 * */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ProjectEuler
{
    class Problem2 : IProblem
    {
        public void Run()
        {
            Fib(1);
            Console.WriteLine();
            Console.WriteLine("\n\n Sum of even valued numbers from first four million of fibonaci series is : " + s);
        }
        int prev = 0;
        int s = 0;
        void Fib(int n)
        {
            int f = prev + n;
            if (f > 4000000) { return; }
            Console.Write(" {0} ", f);
            if (checkEven(f))
            {
                s += f;
            }
            prev = n;
            Fib(f);
        }
        bool checkEven(int n)
        {
            if (n % 2 == 0)
            {
                return true;
            }
            return false;
        }
    }
}
